In [1]:
import pandas as pd
import random
import numpy as np

In [2]:
dados = pd.read_csv("/content/census.csv")
dados.head()

age          workclass  final-weight   education  education-num  \
0   39          State-gov         77516   Bachelors             13   
1   50   Self-emp-not-inc         83311   Bachelors             13   
2   38            Private        215646     HS-grad              9   
3   53            Private        234721        11th              7   
4   28            Private        338409   Bachelors             13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital-gain  capital-loos  hour-per-week  native-country  income  
0          2174             0             40   United-States   <=50K  
1             0             0             13   United-States   <=50K  
2             0             0             40   United-States   <=50K  
3             0             0             40   United-States   <=50K  
4             0             0             40            Cuba   <=50K

In [ ]:
dados.shape

(32561, 15)

#Amostragem Aleatória Simples

In [ ]:
df_amostra_simples = dados.sample(n=100)
df_amostra_simples.shape

(100, 15)

In [ ]:
df_amostra_simples.head()

age      workclass  final-weight      education  education-num  \
8135    23        Private         82998   Some-college             10   
18298   33      Local-gov         27959        HS-grad              9   
21876   35      Local-gov        302149      Bachelors             13   
20586   67   Self-emp-inc        116517      Bachelors             13   
5251    36      Local-gov        196529        Masters             14   

            marital-status       occupation    relationship  \
8135         Never-married            Sales   Not-in-family   
18298        Never-married    Other-service       Unmarried   
21876   Married-civ-spouse            Sales         Husband   
20586              Widowed    Other-service       Unmarried   
5251    Married-civ-spouse   Prof-specialty            Wife   

                      race      sex  capital-gain  capital-loos  \
8135                 White     Male             0             0   
18298   Amer-Indian-Eskimo     Male             0             0   
21876   Asian-Pac-Islander     Male          7298             0   
20586                White   Female             0             0   
5251                 White   Female             0             0   

       hour-per-week  native-country  income  
8135              30   United-States   <=50K  
18298             40   United-States   <=50K  
21876             40     Philippines    >50K  
20586             35   United-States   <=50K  
5251              40   United-States    >50K

In [ ]:
def amostragem_aletoria(dados, n_amostras):
  return dados.sample(n=n_amostras)


#Amostragem sistemática

In [ ]:
dados.shape[0]/100

325.61

In [ ]:
random.seed(21)
random.randint(0, 325)

84

In [ ]:
np.arange(68, dados.shape[0], step=325)

array([   68,   393,   718,  1043,  1368,  1693,  2018,  2343,  2668,
        2993,  3318,  3643,  3968,  4293,  4618,  4943,  5268,  5593,
        5918,  6243,  6568,  6893,  7218,  7543,  7868,  8193,  8518,
        8843,  9168,  9493,  9818, 10143, 10468, 10793, 11118, 11443,
       11768, 12093, 12418, 12743, 13068, 13393, 13718, 14043, 14368,
       14693, 15018, 15343, 15668, 15993, 16318, 16643, 16968, 17293,
       17618, 17943, 18268, 18593, 18918, 19243, 19568, 19893, 20218,
       20543, 20868, 21193, 21518, 21843, 22168, 22493, 22818, 23143,
       23468, 23793, 24118, 24443, 24768, 25093, 25418, 25743, 26068,
       26393, 26718, 27043, 27368, 27693, 28018, 28343, 28668, 28993,
       29318, 29643, 29968, 30293, 30618, 30943, 31268, 31593, 31918,
       32243])

In [ ]:
def amostragem_sistematica(dados, n_amostras):
  intervalo = dados.shape[0]//n_amostras
  random.seed(21)
  
  inicio = random.randint(0, intervalo)
  indices = np.arange(inicio, dados.shape[0], step=intervalo)
  amostra_sis = dados.iloc[indices]
  return amostra_sis

In [ ]:
df_sis = amostragem_sistematica(dados, 100)
df_sis.shape

(100, 15)

In [ ]:
df_sis.head()

age          workclass  final-weight      education  education-num  \
84     44            Private        343591        HS-grad              9   
409    32            Private        364657   Some-college             10   
734    45                  ?         51164   Some-college             10   
1059   45            Private        185385        HS-grad              9   
1384   37   Self-emp-not-inc        137314        HS-grad              9   

           marital-status        occupation    relationship    race      sex  \
84               Divorced      Craft-repair   Not-in-family   White   Female   
409    Married-civ-spouse   Exec-managerial         Husband   White     Male   
734    Married-civ-spouse                 ?            Wife   Black   Female   
1059   Married-civ-spouse      Craft-repair         Husband   White     Male   
1384   Married-civ-spouse   Exec-managerial         Husband   White     Male   

      capital-gain  capital-loos  hour-per-week  native-country  income  
84           14344             0             40   United-States    >50K  
409              0             0             50   United-States   <=50K  
734              0             0             40   United-States   <=50K  
1059             0             0             47   United-States    >50K  
1384             0             0             60   United-States   <=50K

#Amostragem por Grupos

In [ ]:
dados.shape[0] // 10

3256

In [ ]:
grupos = []
id_grupo = 0
count = 0

for _ in dados.iterrows():
  grupos.append(id_grupo)
  count  += 1

  if count > 3256:
    count = 0
    id_grupo += 1

In [ ]:
len(grupos)

32561

In [ ]:
np.unique(grupos, return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([3257, 3257, 3257, 3257, 3257, 3257, 3257, 3257, 3257, 3248]))

In [ ]:
dados['grupo'] = grupos
dados.head()

age          workclass  final-weight   education  education-num  \
0   39          State-gov         77516   Bachelors             13   
1   50   Self-emp-not-inc         83311   Bachelors             13   
2   38            Private        215646     HS-grad              9   
3   53            Private        234721        11th              7   
4   28            Private        338409   Bachelors             13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital-gain  capital-loos  hour-per-week  native-country  income  grupo  
0          2174             0             40   United-States   <=50K      0  
1             0             0             13   United-States   <=50K      0  
2             0             0             40   United-States   <=50K      0  
3             0             0             40   United-States   <=50K      0  
4             0             0             40            Cuba   <=50K      0

In [ ]:
random.randint(0, 9)

6

In [ ]:
df_agrupamento = dados[dados['grupo'] == 6]
df_agrupamento.shape

(3257, 16)

In [ ]:
def amostragem_agrupamento(dados, n_grupos): 
  intervalo = dados.shape[0] // n_grupos

  grupos = []
  id_grupo = 0
  count = 0

  for _ in dados.iterrows():
    grupos.append(id_grupo)
    count  += 1

    if count > intervalo:
      count = 0
      id_grupo += 1

  dados['grupo'] = grupos
  dados.head()

  grupo_s = random.randint(0, n_grupos)
  return dados[dados['grupo'] == grupo_s]

In [ ]:
df_agrupamento = amostragem_agrupamento(dados, 100)
df_agrupamento.shape, df_agrupamento['grupo'].value_counts()

((326, 16), 88    326
 Name: grupo, dtype: int64)

#Amostragem estratificada

In [3]:
from sklearn.model_selection import StratifiedShuffleSplit

In [4]:
dados['income'].value_counts()

 <=50K    24720
 >50K      7841
Name: income, dtype: int64

In [7]:
dados['income'].value_counts()[1]/dados.shape[0], dados['income'].value_counts()[0]/dados.shape[0]

(0.2408095574460244, 0.7591904425539756)

In [11]:
100/dados.shape[0]

0.0030711587481956942

In [12]:
split = StratifiedShuffleSplit(test_size=(100/dados.shape[0]))

for x, y in split.split(dados, dados['income']):
  df_x = dados.iloc[x]
  df_y = dados.iloc[y]

In [13]:
df_x.shape

(32461, 15)

In [14]:
df_y.shape

(100, 15)

In [16]:
df_y['income'].value_counts()

 <=50K    76
 >50K     24
Name: income, dtype: int64